version: "2"

services:
  core:
    stdin_open: true
    tty: true
    container_name: core_container
    build: .
    command: bash -c "python manage.py makemigrations --merge && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/src
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db

  db:
    container_name: db_container
    image: postgres:9.6.16
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testing321
      - POSTGRES_DB=mydb
    volumes:
      - ./database:/var/lib/postgresql/data
